all:
	gcc-5 -Wall src/omp_buckets.c -o omp_buckets -fopenmp -O3

vnode:
	gcc -Wall src/omp_buckets.c -o omp_buckets -fopenmp

zeus:
	gcc -Wall src/omp_buckets.c -o omp_buckets -fopenmp -O3

run:
	./omp_buckets
